# config_sdf.yaml
output_dir: /home/dmsm/gi.catalani/Projects/mario_challenge/airfrans_task/

wandb:
  project: airfrans_sdf

dataset:
  root_path: /scratch/dmsm/gi.catalani/Airfrans/Dataset/
  task: scarce

optim:
  batch_size: 4
  epochs: 1000
  inner_steps: 3
  lr_inr: 5e-5
  lr_code: 0.01
  meta_lr_code: 5e-5
  num_points: 5000

inr:
  model_type: fourier_features
  target_field: implicit_distance
  task: full
  input_dim: 2
  output_dim: 1
  latent_dim: 8
  depth: 5
  hidden_dim: 256
  activation: relu
  w0: null
  use_latent: true
  modulate_scale: false
  modulate_shift: true
  hypernet_depth: 1
  hypernet_width: 128
  frequency_embedding: gaussian
  include_input: true
  scale: 0.5
  num_frequencies: 32
  max_frequencies: 8
  base_frequency: 1.25
  last_activation: null
  loss_type: mse
  add_cond_in: false
  add_sdf_in: false
  global_norm: false
  is_input: true

restart_training: false
saved_model_path: null  # e.g. trainings/.../best.pt
