saved_model_path:
restart_training: False

dataset:
  root_path: /scratch/dmsm/gi.catalani/Airfrans/Dataset/
  task: scarce
  train_latents_path: /home/dmsm/gi.catalani/Projects/mario_challenge/airfrans_task/trainings/training_sdf_20250926-102318/modulations/scarce_train_8.npz
  test_latents_path:  /home/dmsm/gi.catalani/Projects/mario_challenge/airfrans_task/trainings/training_sdf_20250926-102318/modulations/scarce_test_8.npz

optim:
  batch_size: 4
  batch_size_val: 
  lr_inr : 1e-3
  epochs : 2000
  lr_mlp : 1e-4
  weight_decay_mlp: 0
  num_points: 10000


inr:
  model_type : "ms_fourier_features"
  latent_dim : 10 #set this to dim latent geom + inflow condtions dim
  in_dim : 3
  out_dim : 4
  out_scalar_dim : 0
  depth : 6
  hidden_dim : 256
  w0 :
  use_latent: True
  modulate_scale: False
  modulate_shift: True
  hypernet_depth: 3
  hypernet_width: 256
  frequency_embedding: 'gaussian'
  include_input: True
  scale: [1,2]
  num_frequencies: 64
  max_frequencies: 8
  base_frequency: 1.25
  last_activation: 
  loss_type: "mse"
  add_cond_in: False
  add_sdf_in: 
  global_norm: False


